require 'capybara/rails'
require 'capybara/rspec'
require 'debugger'
require 'devise'
require 'factory_girl_rails'
require 'fakeweb'
require 'ffaker'
require 'fuubar'
require 'launchy'
require 'letter_opener'
require 'rack-livereload'
require 'rspec-rails'
require 'shoulda-matchers'

Fog.mock! # this mocks out all AWS calls - really nice
